/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarysystem;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import librarysystem.gui.Login;

/**
 *
 * @author Adam
 */
public class Main extends javax.swing.JFrame {
    private static final int L = 10;
    private static final int S = 50;
    private static final int N = 20;
    /**
     * Creates new form LibrarySystem
     */
    public Main() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.addWindowListener(new WindowAdapter(){
        @Override
        public void windowClosing(WindowEvent event){
            exitProcedure();
        }
    });
    }
    
    public static void exitProcedure(){
        Librarian.write();
        Student.write();
        Book.write();
        System.exit(0);
    }
    
    public static boolean isValidName(String name){
        if(name.matches("[a-zA-Z\\s]+"))
        return true;
        JOptionPane.showMessageDialog(null,"invalid input , please check name fields for proper input","invalid input",0);
        return false;
    }
    
    public static boolean isValidNo(String No){
        if(No.matches("[+]?(\\d)+"))
        return true;
        JOptionPane.showMessageDialog(null,"invalid input , please check contact number field for proper input","invalid input",0);
        return false;
    }
    
    public static boolean isValidText(String text){
        if(text.matches("[\\w(\\s)*\\.,]+"))
        return true;
        JOptionPane.showMessageDialog(null,"invalid input , please check text fields for proper input","invalid input",0);
        return false;
    }
    
    public static boolean isValid(String string){
        if(string.matches("[[\\S]&&[^\"]]+"))
        return true;
        JOptionPane.showMessageDialog(null,"invalid input , please check the fields for proper input","invalid input",0);
        return false;
    }
    
    public static boolean isValidEmail(String email){
        if(email.matches("^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$"))
        return true;
        JOptionPane.showMessageDialog(null,"invalid input , please check the email field for proper input","invalid input",0);
        return false;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        aLoginButton = new javax.swing.JButton();
        lLoginButton = new javax.swing.JButton();
        lLoginButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library System");
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(400, 400));
        setName("Library System"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Library Managment");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        aLoginButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        aLoginButton.setText("Admin Login");
        aLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aLoginButtonActionPerformed(evt);
            }
        });

        lLoginButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lLoginButton.setText("Librarian Login");
        lLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lLoginButtonActionPerformed(evt);
            }
        });

        lLoginButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lLoginButton1.setText("Student Login");
        lLoginButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lLoginButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aLoginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lLoginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lLoginButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(204, 204, 204))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(43, 43, 43)
                .addComponent(aLoginButton, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addGap(43, 43, 43)
                .addComponent(lLoginButton, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addGap(43, 43, 43)
                .addComponent(lLoginButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aLoginButtonActionPerformed
        dispose();
        Login frame = new Login("Admin");
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_aLoginButtonActionPerformed

    private void lLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lLoginButtonActionPerformed
        dispose();
        Login frame = new Login("Librarian");
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_lLoginButtonActionPerformed

    private void lLoginButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lLoginButton1ActionPerformed
        dispose();
        Login frame = new Login("Student");
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_lLoginButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        Librarian.init(L);
        Librarian.read();
        Book.init(N);
        Book.read();
        Student.init(S);
        Student.read();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Main frame = new Main();
                frame.setVisible(true);
                frame.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aLoginButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton lLoginButton;
    private javax.swing.JButton lLoginButton1;
    private javax.swing.JPanel login;
    // End of variables declaration//GEN-END:variables
}
